### ISSUE TITLE
[EXP currency] A cost system that uses in-game EXP rather than currency

### ISSUE THREAD

**Issue by Brickgard** [erikzimmermann/WarpSystem-IssueTracker#321]
I think it'd be really cool if portals could have the cost option to require a certain amount of levels on a player/user, and remove those levels on use.
The intended effect is along the lines of a portal that costs, say, 15 levels to use.  If a player has less than required, a configurable message such as "You need <LVL_REQ - PLAYER_LVL> more levels to use this portal.", and if they have enough, it consumes those levels in exchange for use.

This is first portal plugin I've found that's developed enough to even consider such a request.  Hopefully this turns out useful; it'd certainly help make some basic in-survival portal uses for me, at least.  (Prevents infinite portal passage without the need of economic features)

Great work, and thank you for a great plugin!

**Comment by erikzimmermann** [comment]
# Todo notes
- [ ] Implement Currency class for different currencies and adapters
- [ ] Currency implementation for FeatureObjects
- [ ] Currency implementation for TeleportManager (replace costs:double with costs:Currency)
- [ ] EXP as new currency
- [ ] EXP option for costs button
- [ ] Updating language files
  - [ ] Replace every Coin usage with %CURRENCY%
  - [ ] Add EXP_Currency: 'Level(s)'
